SET check_function_bodies = false;
CREATE TYPE public.currencies AS ENUM ('TRY', 'USD', 'EUR', 'XAU');
CREATE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;
CREATE TABLE public.accounts (id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid DEFAULT auth.uid() NOT NULL, name text NOT NULL, ledger bigint NOT NULL, currency public.currencies NOT NULL, description text NOT NULL);
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts ADD CONSTRAINT accounts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.accounts ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);
GRANT ALL ON public.accounts TO anon;
GRANT ALL ON public.accounts TO authenticated;
GRANT ALL ON public.accounts TO service_role;
CREATE TABLE public.ledgers (id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid DEFAULT auth.uid() NOT NULL, name text NOT NULL, organization bigint NOT NULL, description text NOT NULL);
ALTER TABLE public.ledgers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ledgers ADD CONSTRAINT ledgers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.ledgers ADD CONSTRAINT ledgers_pkey PRIMARY KEY (id);
ALTER TABLE public.accounts ADD CONSTRAINT accounts_ledger_fkey FOREIGN KEY (ledger) REFERENCES public.ledgers(id);
GRANT ALL ON public.ledgers TO anon;
GRANT ALL ON public.ledgers TO authenticated;
GRANT ALL ON public.ledgers TO service_role;
CREATE TABLE public.organizations (id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid DEFAULT auth.uid() NOT NULL, name text NOT NULL, description text NOT NULL);
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ADD CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.organizations ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);
ALTER TABLE public.ledgers ADD CONSTRAINT ledgers_organization_fkey FOREIGN KEY (organization) REFERENCES public.organizations(id);
GRANT ALL ON public.organizations TO anon;
GRANT ALL ON public.organizations TO authenticated;
GRANT ALL ON public.organizations TO service_role;
CREATE POLICY "Enable insert for authenticated users only" ON public.organizations FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable users to view their own data only" ON public.organizations FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = created_by));
CREATE TABLE public.transactions (id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid NOT NULL, from_account bigint NOT NULL, to_account bigint NOT NULL, amount numeric NOT NULL, description text NOT NULL);
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ADD CONSTRAINT transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.transactions ADD CONSTRAINT transactions_from_account_fkey FOREIGN KEY (from_account) REFERENCES public.accounts(id);
ALTER TABLE public.transactions ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.transactions ADD CONSTRAINT transactions_to_account_fkey FOREIGN KEY (to_account) REFERENCES public.accounts(id);
GRANT ALL ON public.transactions TO anon;
GRANT ALL ON public.transactions TO authenticated;
GRANT ALL ON public.transactions TO service_role;
CREATE EVENT TRIGGER ensure_rls ON ddl_command_end WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO') EXECUTE FUNCTION public.rls_auto_enable();
